---
- hosts: localhost
  connection: local
  vars:
    kubeconfig: /path/to/kubeconfig
    release_name: monitoring
    chart_repo: https://prometheus-community.github.io/helm-charts
    chart_name: kube-prometheus-stack
    chart_namespace: monitoring
    chart_values:
      prometheus:
        service:
          type: LoadBalancer
          servicePort: 9090
      grafana:
        service:
          type: LoadBalancer
          servicePort: 80

  tasks:
    - name: Add Prometheus Community Helm repository
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: "{{ chart_repo }}"

    - name: Create monitoring namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        name: "{{ chart_namespace }}"
        api_version: v1
        kind: Namespace
        state: present

    - name: Deploy Helm chart
      kubernetes.core.helm:
        name: "{{ release_name }}"
        chart_ref: "{{ chart_name }}"
        release_namespace: "{{ chart_namespace }}"
        release_values: "{{ chart_values }}"
        kubeconfig: "{{ kubeconfig }}"
        wait: true
      register: helm_deploy
      until: helm_deploy.status.resources is defined
      retries: 5
      delay: 10

    - name: Show Helm deployment status
      debug:
        msg: "{{ helm_deploy.status }}"