---
- name: Deploy Prometheus Monitoring
  hosts: localhost
  connection: local
  vars:
    kubeconfig: /home/ec2-user/.kube/config
    release_name: monitoring
    chart_repo: https://prometheus-community.github.io/helm-charts
    chart_name: prometheus-community/kube-prometheus-stack
    chart_namespace: monitoring
    # chart_values:
    #   prometheus:
    #     service:
    #       type: LoadBalancer
    #       servicePort: 9090
    #   grafana:
    #     service:
    #       type: LoadBalancer
    #       servicePort: 80
    prometheus_service:
      type: LoadBalancer
      servicePort: 9090
    grafana_service:
      type: LoadBalancer
      servicePort: 80

  tasks:
    - name: Add Prometheus Community Helm repository
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: "{{ chart_repo }}"

    - name: Create monitoring namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        kind: Namespace
        state: present
        name: "{{ chart_namespace }}"

    - name: Deploy Helm chart
      kubernetes.core.helm:
        name: "{{ release_name }}"
        chart_ref: "{{ chart_name }}"
        release_namespace: "{{ chart_namespace }}"
        # release_values: "{{ chart_values }}"
        release_values:
          prometheus:
            service: "{{ prometheus_service }}"
          grafana:
            service: "{{ grafana_service }}"
        kubeconfig: "{{ kubeconfig }}"
        wait: true
      register: helm_deploy
      until: helm_deploy.status.resources is defined
      retries: 5
      delay: 10

    - name: Show Helm deployment status
      ansible.builtin.debug:
        msg: "{{ helm_deploy.status }}"
